# Generated by Django 5.0.2 on 2026-02-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_tovara', models.CharField(db_index=True, max_length=100, verbose_name='Код товара')),
                ('gruppa_tovara', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Группа товара')),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Регион')),
                ('sklad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Склад')),
                ('scheta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Счета')),
                ('data', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Дата')),
                ('dopoln_kol_vo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Дополн. кол-во')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'db_table': 'sales',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['kod_tovara', 'data'], name='sales_kod_tov_5b3618_idx'), models.Index(fields=['gruppa_tovara', 'data'], name='sales_gruppa__c838af_idx'), models.Index(fields=['region'], name='sales_region_16a943_idx')],
            },
        ),
    ]
