# Generated by Django 5.0.14 on 2026-02-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'managed': False, 'ordering': ['-data'], 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.CreateModel(
            name='ReadySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_column='Дата', db_index=True, null=True, verbose_name='Дата')),
                ('diler', models.CharField(blank=True, db_column='Дилер', db_index=True, max_length=100, null=True, verbose_name='Дилер')),
                ('klient_id', models.FloatField(blank=True, db_column='Клиент_ИД', null=True, verbose_name='Клиент ИД')),
                ('klient', models.CharField(blank=True, db_column='Клиент', max_length=255, null=True, verbose_name='Клиент')),
                ('invoice_sid', models.BigIntegerField(blank=True, db_column='Инвоиcе_CИД', db_index=True, null=True, verbose_name='Инвоиcе CИД')),
                ('tip', models.CharField(blank=True, db_column='Тип', max_length=100, null=True, verbose_name='Тип')),
                ('tip_organizacii', models.CharField(blank=True, db_column='Тип_организации', max_length=100, null=True, verbose_name='Тип организации')),
                ('produkt', models.CharField(blank=True, db_column='Продукт', db_index=True, max_length=255, null=True, verbose_name='Продукт')),
                ('gruppa_produktov', models.CharField(blank=True, db_column='Группа_продуктов', db_index=True, max_length=100, null=True, verbose_name='Группа продуктов')),
                ('kolichestvo', models.FloatField(blank=True, db_column='Количество', null=True, verbose_name='Количество')),
                ('ves_kg', models.FloatField(blank=True, db_column='Вес_кг', null=True, verbose_name='Вес(кг)')),
                ('obshchaya_summa', models.FloatField(blank=True, db_column='Общая_сумма', null=True, verbose_name='Общая сумма')),
                ('dokhod', models.FloatField(blank=True, db_column='Доход', null=True, verbose_name='Доход')),
                ('valyuta', models.CharField(blank=True, db_column='Валюта', max_length=10, null=True, verbose_name='Валюта')),
                ('tovary', models.CharField(blank=True, db_column='ТОВАРЫ', db_index=True, max_length=255, null=True, verbose_name='Товары')),
                ('year', models.IntegerField(blank=True, db_column='Год', db_index=True, help_text='Год из файла (2024 или 2025)', null=True, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Готовая продажа',
                'verbose_name_plural': 'Готовые продажи',
                'db_table': 'ready_sales',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['data', 'diler'], name='ready_sales_Дата_c5f831_idx'), models.Index(fields=['gruppa_produktov', 'data'], name='ready_sales_Группа__ea0a67_idx'), models.Index(fields=['tovary', 'year'], name='ready_sales_ТОВАРЫ_1b3001_idx')],
            },
        ),
    ]
