# Generated by Django 5.0.14 on 2026-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sale_options_readysale'),
    ]

    operations = [
        migrations.AddField(
            model_name='readysale',
            name='sheet_name',
            field=models.CharField(blank=True, db_column='Лист', db_index=True, help_text='Название листа в Excel файле', max_length=50, null=True, verbose_name='Лист'),
        ),
    ]
