# Generated by Django 5.0.14 on 2026-02-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_readysale_sheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readysale',
            name='klient',
            field=models.CharField(blank=True, db_column='Клиент', db_index=True, max_length=255, null=True, verbose_name='Клиент'),
        ),
        migrations.AddIndex(
            model_name='readysale',
            index=models.Index(fields=['klient', 'data'], name='ready_sales_Клиент_99294f_idx'),
        ),
    ]
