# Generated by Django 5.0.14 on 2026-02-23 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_expensecategory_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание работы')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Бюджет')),
                ('assigned_employees', models.TextField(blank=True, help_text='Список сотрудников через запятую', verbose_name='Прикреплённые сотрудники')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('IN_PROGRESS', 'В процессе'), ('ON_HOLD', 'На паузе'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено')], default='PLANNED', max_length=20, verbose_name='Процесс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reports_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reports_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил последний раз')),
            ],
            options={
                'verbose_name': 'Отчёт по работе',
                'verbose_name_plural': 'Отчёты по выполненным работам',
                'db_table': 'work_reports',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_reports/%Y/%m/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.workreport', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Фотография отчёта',
                'verbose_name_plural': 'Фотографии отчётов',
                'db_table': 'work_report_photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['date', 'status'], name='work_report_date_de9cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['created_by'], name='work_report_created_bd9448_idx'),
        ),
    ]
