# Generated by Django 5.0.14 on 2026-02-23 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workreport_workreportphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreport',
            name='assigned_employees',
        ),
        migrations.AddField(
            model_name='workreport',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role__in': ['ADMIN', 'MANAGER']}, related_name='assigned_work_reports', to=settings.AUTH_USER_MODEL, verbose_name='Прикреплённые сотрудники'),
        ),
    ]
