# Generated by Django 5.0.14 on 2026-02-23 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_workreport_assigned_employees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название каталога')),
                ('catalog_type', models.CharField(choices=[('COLD', 'Холодная серия'), ('WARM', 'Теплая серия')], max_length=10, verbose_name='Тип каталога')),
                ('pdf_file', models.FileField(upload_to='catalogs/pdf/%Y/%m/', verbose_name='PDF файл')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='catalogs/previews/%Y/%m/', verbose_name='Превью (первая страница)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalogs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_catalogs', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Каталог продукции',
                'verbose_name_plural': 'Каталоги продукции',
                'db_table': 'product_catalogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
