# Generated by Django 5.0.14 on 2026-02-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productcatalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('experience_years', models.CharField(help_text="Например: '5 лет' или '10 лет'", max_length=50, verbose_name='Стаж работы')),
                ('client_name', models.CharField(help_text='Название компании клиента из списка', max_length=255, verbose_name='Клиентское название')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('partners', models.JSONField(default=list, help_text='Список партнёров/дилеров, с которыми работает клиент', verbose_name='Партнёры (дилеры)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_cards/photos/%Y/%m/', verbose_name='Фото клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_cards', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_client_cards', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Карточка клиента',
                'verbose_name_plural': 'Карточки клиентов',
                'db_table': 'client_cards',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
