# Generated by Django 5.0.14 on 2026-02-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_clientcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='email',
            field=models.EmailField(blank=True, help_text='Электронная почта клиента', max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clientcard',
            name='phone',
            field=models.CharField(blank=True, help_text='Контактный телефон клиента', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='clientcard',
            name='position',
            field=models.CharField(blank=True, help_text='Должность клиента в компании', max_length=150, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='clientcard',
            name='start_date',
            field=models.DateField(blank=True, help_text='Дата начала работы с клиентом', null=True, verbose_name='Дата начала сотрудничества'),
        ),
    ]
