# Generated by Django 5.0.14 on 2026-02-23 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_clientcard_email_clientcard_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True, help_text='Автоматически проставляется при создании', verbose_name='Дата обхода')),
                ('work_description', models.TextField(help_text='Подробное описание работы выполненной во время визита', verbose_name='Описание проделанной работы')),
                ('suggestions', models.TextField(blank=True, help_text='Предложения от клиента', verbose_name='Предложения')),
                ('complaints', models.TextField(blank=True, help_text='Жалобы от клиента', verbose_name='Жалобы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')),
                ('client_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_reports', to='api.clientcard', verbose_name='Карточка клиента')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visit_reports', to=settings.AUTH_USER_MODEL, verbose_name='Создано менеджером')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_visit_reports', to=settings.AUTH_USER_MODEL, verbose_name='Изменено менеджером')),
            ],
            options={
                'verbose_name': 'Отчет о посещении клиента',
                'verbose_name_plural': 'Отчеты о посещениях клиентов',
                'db_table': 'client_visit_reports',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='visit_reports/photos/%Y/%m/', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('visit_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.clientvisitreport', verbose_name='Отчет о посещении')),
            ],
            options={
                'verbose_name': 'Фотография отчета',
                'verbose_name_plural': 'Фотографии отчетов',
                'db_table': 'visit_report_photos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
