# Generated by Django 5.0.14 on 2026-02-23 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_clientvisitreport_visitreportphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisitreport',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, help_text='Менеджер, которому назначено задание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visit_reports', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный менеджер'),
        ),
    ]
