# Generated by Django 5.0.14 on 2026-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_clientvisitreport_assigned_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='readysale',
            name='region',
            field=models.CharField(blank=True, db_column='Регион', db_index=True, max_length=100, null=True, verbose_name='Регион'),
        ),
        migrations.AddIndex(
            model_name='readysale',
            index=models.Index(fields=['region', 'diler'], name='ready_sales_Регион_34c372_idx'),
        ),
    ]
