# Generated by Django 5.0.14 on 2026-02-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_readysale_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_tovara', models.CharField(db_column='КОД_ТОВАРА', db_index=True, max_length=100, verbose_name='Код товара')),
                ('year', models.IntegerField(db_column='Год', db_index=True, verbose_name='Год')),
                ('month', models.IntegerField(db_column='Месяц', db_index=True, verbose_name='Месяц (1-12)')),
                ('plan_kg', models.FloatField(blank=True, db_column='План_кг', null=True, verbose_name='План (кг)')),
            ],
            options={
                'verbose_name': 'План продаж',
                'verbose_name_plural': 'Планы продаж',
                'db_table': 'sales_plan',
                'ordering': ['year', 'month', 'kod_tovara'],
                'indexes': [models.Index(fields=['year', 'month'], name='sales_plan_Год_53ab47_idx'), models.Index(fields=['kod_tovara', 'year'], name='sales_plan_КОД_ТОВ_5851b2_idx')],
                'unique_together': {('kod_tovara', 'year', 'month')},
            },
        ),
    ]
