# Generated by Django 6.0.2 on 2026-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_salesplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesplan',
            options={'ordering': ['year', 'month', 'region', 'kod_tovara'], 'verbose_name': 'План продаж', 'verbose_name_plural': 'Планы продаж'},
        ),
        migrations.AlterUniqueTogether(
            name='salesplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salesplan',
            name='baza',
            field=models.CharField(blank=True, db_column='База', db_index=True, default='', max_length=100, verbose_name='База'),
        ),
        migrations.AddField(
            model_name='salesplan',
            name='region',
            field=models.CharField(blank=True, db_column='Регион', db_index=True, default='', max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterUniqueTogether(
            name='salesplan',
            unique_together={('kod_tovara', 'year', 'month', 'region', 'baza')},
        ),
        migrations.AddIndex(
            model_name='salesplan',
            index=models.Index(fields=['region', 'year', 'month'], name='sales_plan_Регион_738e5f_idx'),
        ),
    ]
