# Generated by Django 6.0.2 on 2026-02-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_readysale_add_gruppa_tovara'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesplan',
            name='gruppa_tovara',
            field=models.CharField(blank=True, db_column='Группа_товара', db_index=True, help_text='Группа товара из таблицы sales (по коду товара)', max_length=100, null=True, verbose_name='Группа товара'),
        ),
    ]
