# Generated by Django 6.0.2 on 2026-03-11 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_salesplan_add_gruppa_tovara'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('color', models.CharField(choices=[('gray', 'Серый'), ('blue', 'Синий'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), ('red', 'Красный'), ('purple', 'Фиолетовый')], default='gray', max_length=20, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Колонка доски',
                'verbose_name_plural': 'Колонки доски',
                'db_table': 'kanban_columns',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('tags', models.CharField(blank=True, default='', max_length=255, verbose_name='Теги (через запятую)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в колонке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.kanbancolumn', verbose_name='Колонка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'kanban_tasks',
                'ordering': ['column__order', 'order'],
            },
        ),
    ]
