# Generated by Django 6.0.2 on 2026-03-11 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_kanban_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон KPI',
                'verbose_name_plural': 'Шаблоны KPI',
                'db_table': 'kpi_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год')], default='month', max_length=10, verbose_name='Тип периода')),
                ('period_year', models.PositiveIntegerField(verbose_name='Год')),
                ('period_number', models.PositiveIntegerField(help_text='Месяц (1–12), квартал (1–4) или год (1)', verbose_name='Номер периода')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Базовая зарплата')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('closed', 'Закрыт')], default='active', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_records_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_records', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='api.kpitemplate', verbose_name='Шаблон KPI')),
            ],
            options={
                'verbose_name': 'Запись KPI',
                'verbose_name_plural': 'Записи KPI',
                'db_table': 'kpi_records',
                'ordering': ['-period_year', '-period_number'],
                'unique_together': {('manager', 'period_type', 'period_year', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='KPITemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название пункта')),
                ('unit', models.CharField(choices=[('kg', 'Кг'), ('pcs', 'Штук'), ('sum', 'Сум'), ('usd', 'USD'), ('pct', '%'), ('other', 'Другое')], default='kg', max_length=20, verbose_name='Единица измерения')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Например: 0.60 = 60% от базовой зарплаты', max_digits=5, verbose_name='Вес пункта')),
                ('min_threshold', models.DecimalField(decimal_places=2, default=0.85, help_text='Если выполнение ниже — пункт не засчитывается (например: 0.85 = 85%)', max_digits=5, verbose_name='Мин. порог выполнения')),
                ('max_threshold', models.DecimalField(decimal_places=2, default=1.2, help_text='Выполнение выше этого значения обрезается (например: 1.20 = 120%)', max_digits=5, verbose_name='Макс. порог (cap)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.kpitemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пункт шаблона KPI',
                'verbose_name_plural': 'Пункты шаблона KPI',
                'db_table': 'kpi_template_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KPIRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Таргет (план)')),
                ('fact_auto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Факт (авто)')),
                ('fact_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Факт (ручной)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_items', to='api.kpirecord', verbose_name='Запись KPI')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_items', to='api.kpitemplateitem', verbose_name='Пункт шаблона')),
            ],
            options={
                'verbose_name': 'Пункт записи KPI',
                'verbose_name_plural': 'Пункты записи KPI',
                'db_table': 'kpi_record_items',
                'ordering': ['template_item__order'],
            },
        ),
    ]
