# Generated by Django 6.0.2 on 2026-03-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_kpi_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpirecord',
            name='fix_ratio',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='Доля от базовой зарплаты, выплачиваемая всегда. Например: 0.60 = 60%', max_digits=4, verbose_name='Фикса (доля)'),
        ),
    ]
