# Generated by Django 6.0.2 on 2026-03-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_kpi_fix_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitemplateitem',
            name='default_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Подставляется автоматически при создании записи KPI', max_digits=15, null=True, verbose_name='План (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='kpitemplateitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Например: 0.60 = 60% от фиксы идёт на этот пункт', max_digits=5, verbose_name='Доля бонуса'),
        ),
    ]
