# Generated by Django 5.0.14 on 2026-03-22 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_kpi_default_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=60, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('category', models.CharField(help_text='handle, net, sill, seal, slope, blind, espagnolette…', max_length=60, verbose_name='Категория')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за единицу (сум)')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица (шт / пог.м / компл)')),
                ('price_mode', models.CharField(choices=[('fixed', 'За штуку (фиксированно)'), ('per_width', 'Пог.м по ширине'), ('per_height', 'Пог.м по высоте'), ('per_perimeter', 'Пог.м по периметру')], max_length=20, verbose_name='Режим расчёта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
                'db_table': 'cfg_accessory',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlassOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='Формула (4-16-4)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('u_value', models.CharField(blank=True, max_length=30, verbose_name='Теплопередача (U)')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=1.0, help_text='1.0 = базовый, 1.35 = +35% и т.д.', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Коэффициент к цене стекла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Стеклопакет',
                'verbose_name_plural': 'Стеклопакеты',
                'db_table': 'cfg_glass_option',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProfileColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(help_text='Пример: ral-9016, lam-staufer-mocca', max_length=60, unique=True, verbose_name='Код цвета')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('color_type', models.CharField(choices=[('ral', 'RAL'), ('lamination', 'Ламинация')], max_length=20, verbose_name='Тип')),
                ('tier', models.CharField(choices=[('white', 'Белый'), ('colored', 'Цветной RAL'), ('laminated', 'Ламинированный')], max_length=20, verbose_name='Ценовой тир')),
                ('hex', models.CharField(max_length=7, verbose_name='Hex цвет')),
                ('highlight_hex', models.CharField(max_length=7, verbose_name='Hex блик (светлее)')),
                ('shadow_hex', models.CharField(max_length=7, verbose_name='Hex тень (темнее)')),
                ('texture', models.CharField(blank=True, default='', help_text='Относительный путь: /textures/lamination/filename.png', max_length=200, verbose_name='Путь к текстуре')),
                ('materials', models.JSONField(default=list, help_text='Список: ["PVC"], ["aluminum"] или ["PVC","aluminum"]', verbose_name='Совместимые материалы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Цвет профиля',
                'verbose_name_plural': 'Цвета профиля',
                'db_table': 'cfg_profile_color',
                'ordering': ['tier', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(help_text='Латинские буквы и цифры, без пробелов. Пример: akfa-60', max_length=50, unique=True, verbose_name='Код серии')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('material', models.CharField(choices=[('PVC', 'ПВХ'), ('aluminum', 'Алюминий')], max_length=20, verbose_name='Материал')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('features', models.JSONField(blank=True, default=list, help_text='Список строк — пунктов характеристики. Пример: ["60мм профиль", "3 камеры"]', verbose_name='Особенности')),
                ('categories', models.JSONField(default=list, help_text='Список из: window, door, sliding. Пример: ["window","door"]', verbose_name='Категории изделий')),
                ('min_width', models.PositiveIntegerField(default=400, verbose_name='Мин. ширина (мм)')),
                ('max_width', models.PositiveIntegerField(default=2500, verbose_name='Макс. ширина (мм)')),
                ('min_height', models.PositiveIntegerField(default=400, verbose_name='Мин. высота (мм)')),
                ('max_height', models.PositiveIntegerField(default=2500, verbose_name='Макс. высота (мм)')),
                ('price_per_sqm', models.PositiveIntegerField(default=0, help_text='Только для отображения в карточке серии; расчёт идёт по ставкам материалов.', verbose_name='Справочная цена (сум/м²)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Серия профиля',
                'verbose_name_plural': 'Серии профиля',
                'db_table': 'cfg_series',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_per_m', models.PositiveIntegerField(default=0, verbose_name='Рама белая (сум/пог.м)')),
                ('frame_colored_per_m', models.PositiveIntegerField(default=0, verbose_name='Рама цветная RAL (сум/пог.м)')),
                ('frame_laminated_per_m', models.PositiveIntegerField(default=0, verbose_name='Рама ламинация (сум/пог.м)')),
                ('sash_per_m', models.PositiveIntegerField(default=0, verbose_name='Створка белая (сум/пог.м)')),
                ('sash_colored_per_m', models.PositiveIntegerField(default=0, verbose_name='Створка цветная RAL (сум/пог.м)')),
                ('sash_laminated_per_m', models.PositiveIntegerField(default=0, verbose_name='Створка ламинация (сум/пог.м)')),
                ('imposta_per_m', models.PositiveIntegerField(default=0, verbose_name='Импост белый (сум/пог.м)')),
                ('imposta_colored_per_m', models.PositiveIntegerField(default=0, verbose_name='Импост цветной RAL (сум/пог.м)')),
                ('imposta_laminated_per_m', models.PositiveIntegerField(default=0, verbose_name='Импост ламинация (сум/пог.м)')),
                ('glass_per_sqm', models.PositiveIntegerField(default=0, verbose_name='Стеклопакет базовый (сум/м²)')),
                ('hardware_per_opening', models.PositiveIntegerField(default=0, verbose_name='Фурнитура П/О (сум/шт)')),
                ('hardware_per_sliding', models.PositiveIntegerField(default=0, verbose_name='Фурнитура раздвижная (сум/шт)')),
                ('seal_per_m', models.PositiveIntegerField(default=0, verbose_name='Уплотнитель (сум/пог.м)')),
                ('install_base', models.PositiveIntegerField(default=0, verbose_name='Монтаж базовый (сум/изделие)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='api.series', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Ставки материалов',
                'verbose_name_plural': 'Ставки материалов',
                'db_table': 'cfg_material_rates',
            },
        ),
    ]
