# Generated by Django 5.0.2 on 2026-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_configurator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovaryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovary', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Товары')),
                ('kod_tovara', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код товара')),
                ('gruppa_tovara', models.CharField(blank=True, max_length=100, null=True, verbose_name='Группа товара')),
                ('cvet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('profil_perechen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль перечень')),
                ('is_coded', models.BooleanField(db_index=True, default=False, help_text='True если все поля заполнены', verbose_name='Закодирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Справочник товаров',
                'verbose_name_plural': 'Справочник товаров',
                'db_table': 'tovary_mapping',
                'ordering': ['tovary'],
            },
        ),
    ]
