# Generated by Django 5.0.2 on 2026-05-07 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_diler_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Секторы',
                'db_table': 'sectors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clientcard',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_cards', to='api.sector', verbose_name='Сектор'),
        ),
        migrations.AddField(
            model_name='expense',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='api.sector', verbose_name='Сектор'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='api.sector', verbose_name='Сектор'),
        ),
        migrations.AddField(
            model_name='kanbancolumn',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kanban_columns', to='api.sector', verbose_name='Сектор'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kpi_records', to='api.sector', verbose_name='Сектор'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to='api.sector', verbose_name='Сектор'),
        ),
    ]
