# Generated by Django 5.0.2 on 2026-05-07 06:34

from django.db import migrations


def create_default_sector(apps, schema_editor):
    Sector = apps.get_model('api', 'Sector')
    sector, _ = Sector.objects.get_or_create(
        code='main',
        defaults={'name': 'Основной', 'is_active': True},
    )

    # Assign existing records to the default sector
    for Model in [
        apps.get_model('api', 'Expense'),
        apps.get_model('api', 'ExpenseCategory'),
        apps.get_model('api', 'WorkReport'),
        apps.get_model('api', 'KanbanColumn'),
        apps.get_model('api', 'ClientCard'),
        apps.get_model('api', 'KPIRecord'),
    ]:
        Model.objects.filter(sector__isnull=True).update(sector=sector)


def reverse_default_sector(apps, schema_editor):
    pass  # No need to undo data changes on rollback


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_sector_model_and_fks'),
    ]

    operations = [
        migrations.RunPython(create_default_sector, reverse_default_sector),
    ]
