# Generated by Django 5.0.2 on 2026-05-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_create_default_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='gruppa_filters',
            field=models.JSONField(blank=True, default=list, help_text='Список значений gruppa_tovara для этого сектора. Пусто = видеть все данные.', verbose_name='Фильтр по группам товара'),
        ),
    ]
