# Generated by Django 5.0.2 on 2026-04-27 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram chat_id')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram username')),
                ('telegram_first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram имя')),
                ('telegram_last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привязка Telegram',
                'verbose_name_plural': 'Привязки Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Код')),
                ('expires_at', models.DateTimeField(verbose_name='Действителен до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код привязки Telegram',
                'verbose_name_plural': 'Коды привязки Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
