# Generated by Django 5.0.2 on 2026-05-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_sector_model_and_fks'),
        ('authentication', '0003_add_super_admin_role_and_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='null = видит все секторы (для ADMIN/SUPER_ADMIN)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.sector', verbose_name='Сектор'),
        ),
    ]
